version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2022

configuration: Release

platform: Any CPU
assembly_info:
  patch: true
  file: 'LibForge\*\Properties\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0'

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: nuget restore LibForge/LibForge.sln

build:
  project: LibForge/LibForge.sln
  parallel: true
  verbosity: minimal

after_build:
 - >
   7z a LibForge-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\net6.0\LibForge.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\net6.0\MidiCS.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\net6.0-windows\GameArchives.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\net6.0-windows\LibOrbisPkg.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\net6.0-windows\DtxCS.dll
 - >
   7z a ForgeTool-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\net6.0\*
 - >
   7z a ForgeToolGUI-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\net6.0-windows\*
artifacts:
- path: LibForge-%APPVEYOR_BUILD_VERSION%.zip
- path: ForgeTool-%APPVEYOR_BUILD_VERSION%.zip
- path: ForgeToolGUI-%APPVEYOR_BUILD_VERSION%.zip
